// import Navigation from "@/components/Layout/Navigation";
import type { Metadata } from "next";
import "./globals.css";
import iranSansX from "./fonts";
import Footer from "@/src/shared/ui/Footer";
import Divider from "@/src/shared/ui/Divider";
import { Header } from "@/src/widgets/Header/ui";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body className={`${iranSansX.className} bg-[#1F1F1F] overflow-x-hidden`}>
      <Header/>
        {children}
      <Divider className='mt-20 mb-10' />
        <Footer/>
      </body>
    </html>
  );
}
