// import Navigation from "@/components/Layout/Navigation";
import type { Metadata } from 'next';
import './globals.css';
import iranSansX from './fonts';
import Footer from '@/src/shared/ui/Footer';
import Divider from '@/src/shared/ui/Divider';
import { Header } from '@/src/widgets/Header/ui';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body className={`${iranSansX.className}  overflow-x-hidden flex flex-col justify-start items-center`}>
        <Header />
        {children}
        <Divider className="mt-20 mb-10 max-w-[80rem] lg:px-24" />
        <Footer />
      </body>
    </html>
  );
}
